# Change these first
owner: GIOSDK # Your GitHub organization or username, where this repository lives
repo: growingio-sdk-upptime # The name of this repository

sites:
  - name: Android SDK
    url: https://s01.oss.sonatype.org/content/repositories/releases/com/growingio/
  - name: Web JS SDK
    url: https://assets.giocdn.com/sdk/webjs/gdp-full.js
  - name: Minp SDK (Wechat)
    url: https://assets.giocdn.com/sdk/minip/4.3.0/gio-wechat.js
  - name: Apple SDK
    url: https://cdn.jsdelivr.net/cocoa/Specs/6/9/7/GrowingAnalytics/4.4.0/GrowingAnalytics.podspec.json
  - name: HarmonyOS NEXT SDK
    url: https://repo.harmonyos.com/ohpm/@growingio/analytics/-/analytics-2.1.0.har
  - name: Flutter SDK
    url: https://pub.dev/api/archives/growingio_flutter_plugin-4.2.0.tar.gz
  - name: Go SDK
    url: https://github.com/growingio/growingio-sdk-go/tree/v1.0.0
  - name: Python SDK
    url: https://files.pythonhosted.org/packages/44/68/db719d017a50520c3fdef7958afef5ec67c980117d6b7df713c3ad440cd4/growingio_tracker-1.0.5.tar.gz
  - name: Java SDK
    url: https://repo1.maven.org/maven2/io/growing/sdk/java/growingio-java-sdk/1.0.16-cdp/
  - name: Offical Site
    url: https://www.growingio.com

status-website:
  baseUrl: /growingio-sdk-upptime
  logoUrl: https://www.growingio.com/vassets/images/home_v3/gio-logo-primary.svg
  name: GrowingIO
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

workflowSchedule:
  uptime: "*/15 * * * *"

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration